### PR TITLE
Combo 479.483.500.506.515.550.125.529.554.480.614.619.642.654bp23

### PR DESCRIPTION
**Pull request by tucu00**
backporting a series of patches to 2.3

### CODE REVIEW

**Comment by mislam77-zz** [comment]
Since it is a long list of commits that were originally planned for 3.0, do you think it will not break 2.3?
Moreover our QE is not verifying 2.3 anymore.
Although test cases will succeeds, I'm not sure how will it impact the running instances.
I can push it into 2.3 if there could be some sort of QE in your side.
At Yahoo, we don't have any running 2.3 instance.

**Comment by tucu00** [comment]
We'll do the necessary QA for 2.3.

thanks.

**Comment by angeloh** [comment]
+1

**Comment by mislam77-zz** [comment]
+1 pushing

**Pull request merged**
