### PR TITLE
Gh 0048 Update CoordinatorFunctionalSpec with done-flag examples

### PR DESCRIPTION
**Pull request by angeloh**
Change empty string example.

### CODE REVIEW

**Comment by tucu00** [comment]
still is not clear the empty flag example.

I assume what you want to say is that if the done flag is set to empty, then Coordinator looks for the existence of the directory itself. correct?

**Comment by mislam77-zz** [comment]
+1
After getting another +1, I will push it.

**Comment by tucu00** [comment]
+1

**Comment by mislam77-zz** [comment]
pushed.

**Pull request closed without merging**
