### PR TITLE
Gh 0023

### PR DESCRIPTION
**Pull request by tucu00**

### CODE REVIEW

**Comment by rvs** [comment]
Well, I can not see a reason why shouldn't it be included to begin with. As you pointed out you already put GH-XXX  into the commit message so all we're arguing about is an extra word prepended to it, right? Of course integrator can do that, but why should we make it any more difficult for the integrator? Makes sense?

**Comment by tucu00** [comment]
if i understand correctly, all the commits of a patch would have a 'Closes GH-XXXX', that is odd, as it still may go several rounds of reviews and changes.

Also, if all commits start with 'Closes' I'd just not use it as it is clear with the 'GH-XXXX' what is the patch for.

**Comment by rvs** [comment]
Ok, so let me try to explain why I would like to see "Closes" in the commit message. It is all about creating cross links between issues and commits that fix them. E.g. I don't really find something like this all that useful: #17 (the part that says Integrated in 24SEP2010 is not really helpful) since I'd rather see an actual link to a commit: http://github.com/yahoo/oozie/issues/issue/25 AND I want to see the link going the other way around from a commit to an issue, just like here: http://github.com/yahoo/oozie/commit/d5ee66488a585ff9cd333e79e0e2e0248a95702f (you can actually click on Closes GH-0025). So that's the rationale.

No, it all is pretty straightforward when we have 1-1 mapping between individual issues and individual commits that fix them. Your question seems to be what happens when we have N-M relationship. Well, lets see. 

### Multiple commits closing a single issue

When you have multiple commits fixing the same issue there's no danger in putting Closes GH-XXX in all of them. In fact, regardless of GitHub magic, I strongly recommend we do that for tracking purposes (git log --grep="GH-XXXX" --pretty=oneline is so amazing in dealing with software archeology that it isn't even funny).

Now, as a separate note: GitHub, unfortunately, has a number of bugs in the area of how it generates the links inside the issues it closes. Sometimes it lists all of the commits that Close that single issue, sometimes just the first one (and sometimes not even the first one! -- I'm trying to reach out to GH folks to see what's going on). That said, one thing is pretty robust -- the backward links (the ones pointing FROM commits to the ISSUES) are very robust and in case of multiple commits fixing a single issue you will see them pointing to the same place.

### A single commit closing multiple issues

You really should think about closing all the issues in that cluster but one as the duplicates of that single one that you keep alive. Once you do that you find yourself in the previous situation.

### Multiple commits fixing multiple issues

This is a variation of the above -- first you reduce your cluster of issues to a single one, and from that point on you're dealing with mltiple commits closing a single issue situation.

Ok. So if it all makes sense to you (to the point where you now feel comfortable putting Closes GH-XXXX into the commit messages) please let me know. If it doesn't -- let me know ASAP ;-)

**Comment by tucu00** [comment]
I'm good.

PS: Are you saying that 'Closes' is special for GH?

**Comment by rvs** [comment]
Yup. "Closes GH-XXXX" triggers a special behavior on GH whenever a commit with such a message inside hits the repo.

**Comment by tucu00** [comment]
we should have started with that then!!!! :)

**Comment by rvs** [comment]
Pulled the changes. Closing a request.

**Pull request closed without merging**
