### PR TITLE
Gh 0480

### PR DESCRIPTION
**Pull request by brookwc**

### CODE REVIEW

**Comment by angeloh** [comment]
Please rename PigMain_BackUp to PigMainWithOrigAPI or other name which indicated using old api.

**Comment by angeloh** [comment]
+1 after fixing above comments

**Comment by brookwc** [comment]
renamed PigMain_Backup to PigMainWithOldAPI

**Comment by mislam77-zz** [comment]
+1 pushing

**Comment by mislam77-zz** [comment]
+1 pushing.

**Pull request closed without merging**
