### PR TITLE
Pull request for the maintenance branch 2.2

### PR DESCRIPTION
**Pull request by rvs**
### The point of this pull request is twofold:
1. have everybody agree on the content of the maintenance branch for 2.2 work.  
2. get an approval to promote the very same changes to master

Please try it out and let me know if it works for you. Once approved I will also tag the following commits with release tags:
- 2.2.0 -> rvs/oozie@ac2ff442dc646dc8eb2ac64bd776f3137dcb450d
- 2.2.1 -> rvs/oozie@394e6ea615cef508d9a3dc7fc789741c009d9827
- 2.2.2 -> rvs/oozie@da5616e8792b7ead2305f01574c81b4b30fa04cc

### CODE REVIEW

**Comment by tucu00** [comment]
I'm GH confused here, besides the point commits aI cannot see what is the diff between the different tags. For example, I cannot see the combo patch applied to master.

What am I missing?

**Comment by rvs** [comment]
This pull request is NOT meant for master. This is a creation of a dedicate maintenance branch. That's why I asked to evaluate each commit separately. Makes sense?

Now, once we are comfortable with the state of the maintenance branch we can cherrypick the same commits into the master. At that point I can create a separate pull request (although the content of the commits will NOT need to be reviewed -- only the mechanics of their application to the master).

Finally, I don't quite understand your question about the tags. Can you, please, restate it?

**Comment by tucu00** [comment]
now it makes sense. disregard my tags question.

**Comment by tucu00** [comment]
+1 

Side question what is in diff between 2.2.1 and 2.2.2 tags besides version bumping? do we need both of them??

**Comment by angeloh** [comment]
change of ojdbc version is the only diff between 2.2.1 and 2.2.2 except version bump.

**Comment by angeloh** [comment]
+1

**Comment by brookwc** [comment]
+1 after unit test is provided for 

3f75f81 Closes GH-0046 Add support the coordiator job submitted to run in far...

**Comment by rvs** [comment]
This has been mostly resolved. There's a sticky issue with tags left, but I'll address it in a separate quasi-pull request.

**Pull request closed without merging**
