### PR TITLE
Fixed GitHub Issue #45 ExtJS Dependency Warning

### PR DESCRIPTION
**Pull request by subtleGradient**

### CODE REVIEW

**Comment by subtleGradient** [comment]
#45

**Comment by tucu00** [comment]
THANKS Thomas, we'll test it and integrate it after doing so.

**Comment by tucu00** [comment]
+1

just tested both with&without extjs lib. 
thanks again.

**Comment by angeloh** [comment]
+1

**Comment by tucu00** [comment]
closing it as I've integrated this pull with an additional commit in pull 244 setting the right link for the documentation HREF.

**Pull request closed without merging**
