### PR TITLE
Gh 0141

### PR DESCRIPTION
**Pull request by brookwc**
this pr is for issue #141

### CODE REVIEW

**Comment by brookwc** [comment]
Commiter only needs to fix one trivial conflict on release-log.txt.

**Comment by angeloh** [comment]
+1

**Comment by mislam77-zz** [comment]
based n feedback going to push.

**Comment by mislam77-zz** [comment]
+1

**Comment by brookwc** [comment]
I checked this pr - it has been pushed already (quite a while ago) - closing.

**Pull request closed without merging**
