### PR TITLE
Closes OOZIE-11 Adding DistCp Action

### PR DESCRIPTION
**Pull request by bansalmayank**
Adding Distcp Action

### CODE REVIEW

**Comment by angeloh** [comment]
add entry to release log

**Comment by mislam77-zz** [comment]
+1

**Comment by angeloh** [comment]
+1

**Comment by mislam77-zz** [comment]
the document is coming.
pushed.

**Comment by inders** [comment]
guys, is the doc published somewhere to highlight the usage of distcp action?

**Pull request closed without merging**
