### PR TITLE
Gh 0106

### LINKED ISSUE #27: add support for a share lib directory in HDFS for action binaries.
Currently every workflow that uses a pig action must bundle the Pig JAR in the workflow lib/ directory.

This is also true for commonly use JARs files across different workflow apps.

By adding a share lib job property, which is added as a secondary lib/ directory, all commons JARs (Pig, Hive) can be added in a /usr/share/lib directory in HDFS and used by multiple workflow applications without having to have a private copy per workflow app.

The location of HDFS share lib would be specified as job property (a later rev of the workflow XML schema may add support for it too)

### LINKED ISSUE #106: add support for an (Oozie) system share lib directory in HDFS for action binaries.
This issue builds on top of GH-0027

The motivation for GH-0027 is to allow workflow apps to easily share a common set of JAR/SO libraries without having to bundle those JAR/SO libs in each workflow app lib/ directory. 

The motivation for this issue is to allow the (Oozie) system to use set a default set of JAR/OS libraries in the workflow application path. A useful feature when a setup is defining a common stack (i.e. for pig, streaming, hive, sqoop, inputformats, UDFs libs, etc) and a workflow app just want to use the stack.

To maintain backward compatibility, by default this system defined 'share lib' directory is not included. Workflow jobs must set a flag in their job properties for the inclusion to happen.

A future version of workflow apps would revert the default behavior.

### PR DESCRIPTION
**Pull request by tucu00**
Closes GH-0027 add support for a share lib directory in HDFS for action binaries.
Closes GH-0106 add support for an (Oozie) system share lib directory

### CODE REVIEW

**Comment by mislam77-zz** [comment]
Would you please include release log file for this commit?

**Comment by angeloh** [comment]
If it is HttpSubmit, isWorkflowJob will be false.

+1 after release log.

**Comment by mislam77-zz** [comment]
+1
Doing the pull.

**Comment by mislam77-zz** [comment]
Done.

**Pull request closed without merging**
