### PR TITLE
Oozie 0007

### PR DESCRIPTION
**Pull request by tucu00**

### CODE REVIEW

**Comment by angeloh** [comment]
+1

**Comment by mislam77-zz** [comment]
+1 pushing.

**Comment by mislam77-zz** [comment]
is it for 2.3 or master?
I plan to do it for master push.

**Comment by mislam77-zz** [comment]
I found out this is for 2.3/
Will there be another one for master?

**Comment by tucu00** [comment]
This is a backport, it is already in master

**Comment by mislam77-zz** [comment]
ok i'm pushing it now.

**Pull request merged**
