### PR TITLE
Gh 0055

### PR DESCRIPTION
**Pull request by brookwc**

### CODE REVIEW

**Comment by tucu00** [comment]
If I understand correctly, with the proposed patch all COORD jobs in the future will be considered for materialization on every materialization run and if the action is far in the future (more than 5 mins) no materialization will happen.

This means that on every materialization run all jobs in the future will be selected and discarded.

Wouldn't be more efficient to make the query on jobs to materialize to do the time filtering?

**Comment by brookwc** [comment]
No, this wont happen. Materialization trigger service will filter out those jobs.

select OBJECT(w) from CoordinatorJobBean w where w.startTimestamp <= :matTime ......

The difference of this patch is it is dealing with a newly submitted job which will be selected for materialization without trigger service kicking in

**Comment by tucu00** [comment]
got it

+1

**Comment by angeloh** [comment]
+1 pushing.

**Comment by rvs** [comment]
+1

And pushed to master.

**Pull request closed without merging**
