### PR TITLE
Gh 0098 new X command pull request

### PR DESCRIPTION
**Pull request by bansalmayank**
X command pull request please ignore pull request 133

### CODE REVIEW

**Comment by brookwc** [comment]
sounds making sense now. +1 

javadoc needs to keep up with this change.

**Comment by tucu00** [comment]
A few more comments on this PR:

XCommand - 77: JOBs does not belong to this class.
XCommand - 105: dryrun does not belong here.
XCommand - 242/260: this is redone in 288 doing a second exception count, we should remove this.
XCommand -385: all logInfo methods don't belong here.

**Comment by bansalmayank** [comment]
Tucu Comments:

A few more comments on this PR:

XCommand - 77: JOBs does not belong to this class.

I think It should be here as it was in Command as well

XCommand - 105: dryrun does not belong here.

I think It should be here as it was in Command as well

XCommand - 242/260: this is redone in 288 doing a second exception count, we should remove this.

Done

XCommand -385: all logInfo methods don't belong here.

I think It should be here as it was in Command as well

this is not an ignore, this is a error for developers as commands are not reusable, remove the 'ignore'

DONE

**Comment by mislam77-zz** [comment]
+1

**Comment by brookwc** [comment]
+1 will push

**Comment by tucu00** [comment]
As far I know we have not finished the discussion on this PR, we
shouldn't push yet.

My comments regarding JOBS, dryrun and loginfo stuff in the base
command still stand.

There are uses for XCommand where none of these things applies, thus
this should not be in the base XCommand class, but in a JobXCommand
class or something like that.

Thanks.

Alejandro

**Comment by bansalmayank** [comment]
I see your point for it is wrongly implemented in older Command class and should not be part of XCommand. We can provide utility classes for that.
However I still think dryrun should be part of XCommand as all the commands are derived from this one and should be having context whether they are running in normal mode or dryrun mode. In the future we may want to change something in Xcommand based on mode of Command which could be dryrun or normal.

I am working on removing job and log parts.

Thanks,
Mayank

**Comment by tucu00** [comment]
Mayank,

Sorry for insisting on this, but there are many commands for which rerun logic does not apply. For example: notification, all the commands that get data from the DB to responde WS calls, recovery commands etc.

I see the value of having a base class having a bunch of convenience methods, but I would argue that is a subclass of XCommand not XCommand itself.

Thanks.

Alejandro

**Comment by bansalmayank** [comment]
Hi Alejandro,

Getting all the commands from the DB are now changed to JPA commands which are no more depends on XCommand.

In XCommand we have some methods like eagerloadstate, loadstate, eagerverifyprecondtion,verifyprecondition which all are not necessarily be used by all the commands. They will be used as and when needed based on the nature of the commands.

We have two overloaded constructors in XCommand one with dryrun and another without dryrun. So commands can construct the object based on their particular needs.

I don't have a problem having a subclass for dryrun but just for dryrun creating the subclass doesn't seems to be a good choice. And Moreover I still see the value of having dryrun flag on the base class as if we want to use that in future in base command itself.

Thanks,
Mayank

**Comment by tucu00** [comment]
I'm confused, JPA Commands are not  queueable commands, we even discussed to rename that class to something like JPAAction or JPAExecutor. But these JPACommands are executed from an XCommand, for example the GetJobCommand.

What am I missing?

Thanks.

**Comment by mislam77-zz** [comment]
I believe we need "dryrun" in XCommand. There could be some code in XCommand that we might need to conditionally execute depending on whether it is in "dryrun" mode.
For example, in dryrun mode , we don't need to execute all instrumentation code. In addition, in future, we might need to add extra debugging for "dryrun" mode. 
Therefore I suggest we keep it an option in the constructor.

**Comment by tucu00** [comment]
Mohammad,

IMO, the XCommand should be agnostic of 'dryrun'. There should be another subclass, *Command that adds the dryrun property for the commands that need it.

By just looking at the WF commands the following commands do not need 'dryrun' functionality:

  DefinitionCommand
  ExternalIdCommand
  JobCommand
  JobsCommand
  KillCommand
  NotificationCommand
  PurgeCommand
  SuspendCommand
  WorkflowActionInfoCommand

My point is, the dryrun logic is something not inherent to XCommand but to subclasses of it.

Thanks.

Alejandro

**Comment by mislam77-zz** [comment]
Hi Alejandro,
As I mentioned in my example. In XCommand itself, the dryrun might be needed to perform some conditionally execution.

WFCommands might not have it now. But in future we might need to do some sort of dryrun. As a matter of fact, people are asking for this. Keeping it in XCommand will be extend-able.

So I still think it is the right place.

I think we need to come to closure soon. 
We can create a separate issue to follow this discussion.

Regards,
Mohammad

**Comment by tucu00** [comment]
Mohammad,

IMO this is a clear case separation of concerns. 

Would you please run this by Andreas to see what is his opinion?

+1 to the patch (with reservations on the dryrun thingy there).

**Comment by mislam77-zz** [comment]
Thanks Alejandro.
I have created an issue to follow it.
https://github.com/yahoo/oozie/issues/issue/379

Will discuss this with Andreas too.

**Comment by brookwc** [comment]
ok, I'll push this pr shortly if no further objection coming up.

**Comment by angeloh** [comment]
pushed.

**Pull request closed without merging**
