### PR TITLE
Gh 0141bp22

### PR DESCRIPTION
**Pull request by brookwc**
This PR is to back port fix to GH-0141 to 2.2 branch.

### CODE REVIEW

**Comment by mislam77-zz** [comment]
+1

**Comment by angeloh** [comment]
+1

**Comment by tucu00** [comment]
+1

the patch looks good (still, it would be nice to have an answer on my question to the alias).

you are posting a backport for 2.3 as well, correct?

**Comment by brookwc** [comment]
Yes, we are gonna backport for 2.3 too.

**Pull request merged**
