### PR TITLE
Gh 0158 new Adding CoordActionInfoXCommand,CoordChangeXCommand,CoordinatorXCommand,CoordJobUpdateCommand,CoordJobsToBeMaterializedCommand and WorkflowXCommand

### PR DESCRIPTION
**Pull request by bansalmayank**
Adding CoordActionInfoXCommand,CoordChangeXCommand,CoordinatorXCommand,CoordJobUpdateCommand,CoordJobsToBeMaterializedCommand and WorkflowXCommand

### CODE REVIEW

**Comment by tucu00** [comment]
how are you planning to commit this patch?

I'd say that we have to commit 98 and 99 as 2 different patches, one for XCommand and one for JPACommand (which by the way I've commented on renaming it) and then incremental patches for the Commands as they migrate

**Comment by bansalmayank** [comment]
I think whosoever will commit will cherry pick only these changes on Xcommand and jpa command.

**Comment by tucu00** [comment]
The idea is at the developer GH-#### branch has exactly what is being committed.

**Comment by angeloh** [comment]
GH-0098-new is not a issue #.

**Pull request closed without merging**
