### PR TITLE
[3.0] GH-0377 Create basic JPA executor for basic coordinator and workflow db access

### LINKED ISSUE #377: Create basic JPA executor for basic coordinator and workflow db access
Move old store service to jpa executor and this patch is only for parent executor classes.

### PR DESCRIPTION
**Pull request by angeloh**
Closes GH-0377 Create basic JPA executor for basic coordinator and workflow db access

### CODE REVIEW

**Comment by angeloh** [comment]
Tucu,

The feedback has been incorporated in the last commit. I also put the responses in all comments above.

**Comment by mislam77-zz** [comment]
+1

**Comment by bansalmayank** [comment]
+1

**Comment by mislam77-zz** [comment]
pushed

**Pull request closed without merging**
