### PR TITLE
Gh 0122 - Added Bundle interfaces and add store functionality

### PR DESCRIPTION
**Pull request by bansalmayank**
Added Bundle interfaces and add store functionality

### CODE REVIEW

**Comment by angeloh** [comment]
+1

**Comment by brookwc** [comment]
+1

**Comment by brookwc** [comment]
i am pulling now.

**Comment by brookwc** [comment]
During pulling, find one more "author" tag, please fix.

will pull again after fix.

**Comment by bansalmayank** [comment]
Closing we don't need it anymore, we will have new pull request for the bundle

**Pull request closed without merging**
