### PR TITLE
Gh 0137

### PR DESCRIPTION
**Pull request by tucu00**
submitting patch for master,  IMO, it should be applied also to the 2.2 branch.

### CODE REVIEW

**Comment by rvs** [comment]
Now that the commit from 2.2 made it to the master branch, here's what I propose instead of your commit:
      http://github.com/rvs/oozie/commit/094f635b567f279e48239043d34db8874d3881f8

Please let me know what do you think.

**Comment by angeloh** [comment]
+1

**Comment by angeloh** [comment]
Please close it if it has been pushed.

**Comment by mislam77-zz** [comment]
Closing

**Pull request closed without merging**
