### PR TITLE
Closes GH-0566 If Java Main exit code !=0, LauncherMapper should the exit

### LINKED ISSUE #566: If Java Main exit code !=0, LauncherMapper should the exit code as the error code
Currently the wf:errorCode(NODE) is fixed to some internal Oozie error codes.

Because of this, a WF app cannot decide what to do base on the Java Main exit code.

### PR DESCRIPTION
**Pull request by tucu00**
Closes GH-0566 If Java Main exit code !=0, LauncherMapper should the exit code as the error code

### CODE REVIEW

**Comment by mislam77-zz** [comment]
ok what about the comment I made "is itt possible 'errorCode' could be null?"

**Comment by mislam77-zz** [comment]
Hi Alejandero,
Could you please address the one unanswered comment?
I want push it soon.

Regards,
Mohammad

**Comment by tucu00** [comment]
Mohammad,

No, it should not be possible, in every place where things can go wrong in the launcher without a System.exit() call the patch is setting ZERO.

**Comment by mislam77-zz** [comment]
+1 pushing.

**Pull request closed without merging**
