### PR TITLE
GH-0416 Fix TestWorkflowActionsRunningGetJPAExecutor and change default db to hsql 

### PR DESCRIPTION
**Pull request by angeloh**
Fix TestWorkflowActionsRunningGetJPAExecutor and change default db to hsql

### CODE REVIEW

**Comment by bansalmayank** [comment]
+1 
Please create issue for derby database to support. As it is broken.

Thanks,
Mayank

**Comment by mislam77-zz** [comment]
+1 after comments

**Comment by angeloh** [comment]
issue is created here:
https://github.com/yahoo/oozie/issues/#issue/418

**Comment by bansalmayank** [comment]
Pushed.

**Pull request merged**
