### PR TITLE
Gh 0064 Create a config to turn on openjpa log

### PR DESCRIPTION
**Pull request by angeloh**
Create a config to turn on openjpa log

### CODE REVIEW

**Comment by mislam77-zz** [comment]
+1

I think Alejandro already gave +1.
So I'm going to push.

**Comment by tucu00** [comment]
wait!!!, this patch is old , is missing the derby DB section in the persistency.xml

**Comment by angeloh** [comment]
Let me update it.

**Comment by tucu00** [comment]
+1

**Pull request merged**
